name: Frontend Security Scan

on: [push, pull_request]

jobs:
  frontend-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
         fetch-depth: 0

      # 1) Talisman scan for secrets
      - name: Run Talisman
        uses: carhartl/talisman-secrets-scan-action@v1.4.0
        

      # 2) OWASP Dependency Check
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "frontend"
          path: "./frontend"
          format: "HTML"
          out: "reports"

      # 3) SonarQube scan
      - name: SonarQube Scan
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=frontend-project \
            -Dsonar.projectName=Frontend \
            -Dsonar.sources=/usr/src/frontend \
            -Dsonar.host.url=http://host.docker.internal:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}


