name: Global Trivy Scan

on: [push, pull_request]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Install Trivy CLI (latest version)
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          trivy --version

      # Run Trivy vulnerability scan on the entire repo
      - name: Run Trivy Repo Scan
        run: |
          trivy fs --security-checks vuln,secret . 
