name: Global Trivy Scan

on: [push, pull_request]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Install Trivy and add to PATH
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          echo "$PWD/bin" >> $GITHUB_PATH

      # Run Trivy filesystem scan on the entire repo
      - name: Run Trivy Repo Scan
        run: |
          trivy fs --security-checks vuln,secret .
